# Global parameters for DVC pipeline
seed: 42

data:
  kaggle_competition: store-sales-time-series-forecasting
  raw_dir: data/raw
  interim_dir: data/interim
  processed_dir: data/processed
  train_ratio: 0.8
  val_ratio: 0.1
  test_ratio: 0.1

features:
  price_base_by_family:
    AUTOMOTIVE: 25.0
    BABY_CARE: 15.0
    BEAUTY: 20.0
    BEVERAGES: 3.5
    BOOKS: 12.0
    BREAD_BAKERY: 2.5
    CELEBRATION: 8.0
    CLEANING: 5.0
    DAIRY: 4.0
    DELI: 6.0
    EGGS: 3.0
    FROZEN_FOODS: 7.0
    GROCERY_I: 4.5
    GROCERY_II: 3.5
    HARDWARE: 18.0
    HOME_AND_KITCHEN: 22.0
    HOME_APPLIANCES: 45.0
    HOME_CARE: 8.0
    LADIESWEAR: 28.0
    LAWN_AND_GARDEN: 15.0
    LINGERIE: 18.0
    LIQUOR_WINE_BEER: 12.0
    MAGAZINES: 5.0
    MEATS: 9.0
    PERSONAL_CARE: 7.0
    PET_SUPPLIES: 10.0
    PLAYERS_AND_ELECTRONICS: 55.0
    POULTRY: 8.0
    PREPARED_FOODS: 6.0
    PRODUCE: 3.0
    SCHOOL_AND_OFFICE_SUPPLIES: 8.0
    SEAFOOD: 12.0
  promotion_discount: 0.15
  store_coefficient_range: [0.85, 1.15]
  temporal_features:
    - day_of_week
    - month
    - year
    - is_weekend
    - is_holiday
    - day_of_month
    - week_of_year

model:
  baseline:
    type: elasticnet
    alpha: 0.1
    l1_ratio: 0.5
  lightgbm:
    objective: regression
    metric: rmse
    boosting_type: gbdt
    num_leaves: 31
    learning_rate: 0.05
    n_estimators: 500
    early_stopping_rounds: 50
    verbose: -1

optuna:
  n_trials: 50
  timeout: 3600
  study_name: lightgbm_demand

optimization:
  objective: revenue
  price_min_ratio: 0.7
  price_max_ratio: 1.3
  max_price_change: 0.2
  solver: SLSQP
